version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      # run tests!
      - run: cat /dev/null | sbt test:test
      # run package
      - run: cat /dev/null | sbt packageBin
#  release:
#    docker:
#        # specify the version you desire here
#        - image: circleci/golang:1.8
#    steps:
#      - run: go get github.com/tcnksm/ghr
#      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v0.0.$CIRCLE_BUILD_NUM $CIRCLE_ARTIFACTS/ || true
#
#workflows:
#  build-and-release:
#    jobs:
#      - build
#      - release